### PR TITLE
Add az cli auth

### PR DESCRIPTION
**Pull request by JCZuurmond**
This PR add the option to use the authentication of the Azure CLI.

### CODE REVIEW

**Comment by JCZuurmond** [comment]
How do we improve testing here?

**Comment by JCZuurmond** [comment]
I think it would be neat to do something similar as they do [here](https://github.com/microsoft/msticpy/blob/db6e6f9f2c66db51f82c986c5d573639eb68909f/msticpy/common/azure_auth_core.py).

Looking at [what is supported](https://docs.microsoft.com/en-us/python/api/azure-identity/azure.identity?view=azure-python), we could add:
- `AzureCliCredential` (as done in this PR)
- `CertificateCredential` : allowing to have a certificate path instead off the secret.
- `EnvironmentCredential` : using environment variables.
- `InteractiveBrowserCredential`: login with browser.
- `ManagedIdentityCredential`: managed identity
- `UsernamePasswordCredential`: user-name password
- `VisualStudioCodeCredential`: visual studio code user.

Except for the `ActiveDirectory Integrated (Windows only)`  it would cover all the currently supported login methods and more.

**Comment by dataders** [comment]
This is incredible, thanks! @NandanHegde15 and I were just talking about how
`ActiveDirectoryIntegrated` wasn't going to work because it requires Active Directory Federation Services which is not ideal IMHO.

**Comment by JCZuurmond** [comment]
Great, I can add the other authentication methods in separate PRs. I think we should do all authentications via `azure.identity`.

**Comment by dataders** [comment]
@JCZuurmond can you open this on https://github.com/mikaelene/dbt-sqlserver ? In #32 we're working on having `dbt-synapse` just inherit the connection class methods from `dbt-sqlserver`. In this way, one will also be able to use the Azure CLI to auth to Azure SQL

**Comment by JCZuurmond** [comment]
Done [here](https://github.com/dbt-msft/dbt-sqlserver/pull/71)

**Pull request closed without merging**
