### PR TITLE
add alter_column_type macro

### LINKED ISSUE #59: issue with snapshot when source table has a new column
[original dbt Slack thread in #dbt-synapse](https://getdbt.slack.com/archives/C01DRQ178LQ/p1628673240003400)

> Think I found a bug in the `0.19.2` version of the dbt-synapse.
> When making a snapshot with a new detected column, it will try this query:
> `alter table <db>.<schema>.<table> add COLUMN <name> <datatype>;`
> This should be:
> `alter table <db>.<schema>.<table> add COLUMN <name> <datatype>;`
> Now you'll receive this error in v0.19.2:
> ```
> Database error: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server]
> [SQL Server]Parse error at line: 2, column: 75:
> Incorrect syntax near 'column'. (103010) (SQLExecDirectW)")
> ```

### LINKED ISSUE #63: alter column type syntax error on incremental models
running an incremental model calls the macro `alter_column_type` which has the incorrect syntax (possibly brought over from sql server?) of `alter table <table_name> add column <column_name> <type>` when it should be `alter table <table_name> add <column_name> <type>`

Here is the log output (model/column names changed)

```
2021-09-23 16:00:50.330909 (Thread-3): Changing col type from character varying(20) to character varying(255) in table <table_name>
2021-09-23 16:00:50.343175 (Thread-3): Using synapse connection <model_name>.
2021-09-23 16:00:50.344859 (Thread-3): On <model_name>: 
    alter table <table_name> add column <alter_column> character varying(255);
    update <table_name> set <alter_column> = <column_name>;
    alter table <table_name> drop column <column_name> cascade;
    alter table <table_name> rename column <alter_column> to <column_name>
  
2021-09-23 16:01:01.595936 (Thread-3): Database error: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Parse e
rror at line: 2, column: 66: Incorrect syntax near 'column'. (103010) (SQLExecDirectW)")
2021-09-23 16:01:01.599486 (Thread-3): On <model_name>: ROLLBACK
2021-09-23 16:01:01.602760 (Thread-3): On <model_name>: Close
2021-09-23 16:01:01.605614 (Thread-3): Error running SQL: macro alter_column_type
```

Possible related to https://github.com/dbt-msft/dbt-synapse/issues/59

### PR DESCRIPTION
**Pull request by dlarsen5**
fixes: https://github.com/dbt-msft/dbt-synapse/issues/63
fixes: https://github.com/dbt-msft/dbt-synapse/issues/59

### CODE REVIEW

**Comment by dataders** [comment]
amazing -- thanks  @dlarsen5 ! can you confirm that this fixes the issue you were seeing? You can test this change by installing dbt-synapse locally with `pip install path/to/dbt-synapse` (or `pip install .` if you're already inside the repo)

the other thing I'd ask would be to add a quick doc to the `CHANGELOG.md`. dbt version `0.21.0` is coming out soon, so that's the most logical place to release it, but if needed, we can release a new patch version of dbt-synapse so you don't have to upgrade your dbt project yet.

**Comment by dlarsen5** [comment]
> can you confirm that this fixes the issue you were seeing?

yep, my model fails without the changes and runs successfully with the changes, so not much of a test case but can confirm changes makes it work

> we can release a new patch version of dbt-synapse so you don't have to upgrade your dbt project yet.

it looks like I can just add the changes as a macro in my dbt project since it overrides the default which makes my models work, so this can be worked into the next release with no need for a patch

**Comment by dlarsen5** [comment]
also @swanderz I'm not sure this fully resolves https://github.com/dbt-msft/dbt-synapse/issues/59 since my case was with incremental models not snapshot models

**Comment by dataders** [comment]
close in https://github.com/dbt-msft/dbt-synapse/issues/63 instead

**Pull request closed without merging**
