### PR TITLE
v1.4.1rc1 - switch dependency dbtsqlserver to dbtfabric

### PR DESCRIPTION
**Pull request by arthurcht**
- bumped __version__.py to v1.4.1rc1
- switched dependency from "dbt-sqlserver~=1.4.0" to "dbt-fabric~=1.4.0rc3"
- updated to inherit new parent dbt-fabric, with failing tests and macros fixed

### CODE REVIEW

**Comment by arthurcht** [comment]
@microsoft-github-policy-service agree company="dataroots"

**Comment by arthurcht** [comment]
@microsoft-github-policy-service agree company="dataroots"

**Comment by prdpsvs** [comment]
@arthurcht , @nszoni , the integration tests are failing. Could you please check?

**Comment by arthurcht** [comment]
thanks @prdpsvs ! to fix [error at "Install dependencies" (i.e. pip install) step](https://github.com/microsoft/dbt-synapse/actions/runs/7873134515/job/21533508831), 
I've removed `pyodbc` from `dev_requirements.txt`. Please run integration tests with latest commit.

(optional) explanation:
`pyodbc` requirement was added, for Mac users to avoid "Symbol not found: _SQLAllocHandle" error.
but `pyodbc` requirement makes `pip install` fail on Windows and, in this case, Ubuntu-latest too.

so removed `pyodbc` requirement, for this PR's integration tests to proceed on Ubuntu-latest,
while documenting alerts for Mac users to resolve this issue. cc @nszoni

**Comment by arthurcht** [comment]
@prdpsvs PR integration tests failing because `AZURE_CLIENT_ID` missing?
could u please check repo's environment variables and help to fix? i don't have repo admin access to view/edit environment variables

**Comment by prdpsvs** [comment]
@arthurcht , Secrets were up to date. I created a new app and updated secrets to make I am not missing on something obvious. Does this have to do anything with taking fabric as a dependency. The connection manager in Fabric adapter went through a few changes. I suspect those changes are causing this error. 

image

**Comment by arthurcht** [comment]
@prdpsvs Secrets [still seem to be null](https://github.com/microsoft/dbt-synapse/actions/runs/7898675115/job/21665640881?pr=191),
secrets_null

and my colleagues and I have successful tests locally with dbt-fabric as dependency.

but as discussed, let's meet to confirm repo's Secrets are correctly configured (per pic below),
and investigate if "fabric as dependency" is root cause.
configure_secrets

**Pull request closed without merging**
